### ISSUE TITLE
Provide config for setup_OpenELIS.py in file 

### ISSUE THREAD

**Issue by bgeVam** [I-TECH-UW/OpenELIS-Global-2#198]
It would be very convenient to provide all the settings that are needed in a settings file (e.g. yml). So when we execute setup_OpenELIS.py, we dont need to do it interactivley.

Proposal (settings.yml):

```
server:
    ip: "127.0.0.1"
    port: "8443"

security:
    keystore:
        password: "abcde12345"
```
